config:
  target: "ws://localhost:3000/websocket" # your app url
  phases:
    - duration: 60
      arrivalRate: 20
  engines:
    meteor: {} # include meteor engine
scenarios:
  - engine: "meteor" # meteor scenario
    flow: # scenario flow
      - login: # login first
          username: USERNAME
          password: PASSWORD
      - call: # then Meteor.call
          name: "method name"
          payload: # make sure payload is Array type
            - _id: "Payload"
      - subscribe: # subscribe to publication
          name: "pub name"
          payload: # make sure payload is Array type
            - "Payload"
